# Generated by Django 5.2.1 on 2025-06-09 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_produit', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('position', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='users.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qrcodes/')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emetteur', models.CharField(max_length=255)),
                ('destinataire', models.CharField(max_length=255)),
                ('date_transaction', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(choices=[('B2B', 'Transaction B2B'), ('B2C', 'Transaction B2C')], max_length=50)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='ligne_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.transaction')),
            ],
        ),
    ]
