# Generated by Django 5.2.1 on 2025-06-23 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(default='', max_length=255)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LotProduit',
            fields=[
                ('numero_lot', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('date_enregistrement', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='lots/')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='core.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_transaction', models.CharField(choices=[('B2B', 'Transaction B2B'), ('B2C', 'Transaction B2C')], max_length=50)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_recues', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_emises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ligne_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_totale', models.PositiveIntegerField()),
                ('lots', models.ManyToManyField(related_name='transactionsLots', to='core.lotproduit')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactionsProduit', to='core.produit')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='core.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='UniteProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_produit', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.CharField(default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='core.lotproduit')),
            ],
        ),
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qrcodes/')),
                ('unite_produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='core.uniteproduit')),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_alerte', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_recues', to=settings.AUTH_USER_MODEL)),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_emises', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.lotproduit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.uniteproduit')),
            ],
        ),
    ]
