# Generated by Django 5.2.1 on 2025-05-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='produit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='core.produit'),
        ),
    ]
