# Generated by Django 5.2.1 on 2025-05-30 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alerte_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date_enregistrement',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
