# Generated by Django 5.2.1 on 2025-06-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('email', models.EmailField(default='default@exemple.com', max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('fournisseur', 'Fournisseur'), ('distributeur', 'Distributeur'), ('gerant', 'Gerant_Pharmacie')], max_length=20)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.compte')),
            ],
        ),
    ]
