# Generated by Django 5.2.1 on 2025-06-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='email',
            field=models.EmailField(default='default@exemple.com', max_length=254, unique=True),
        ),
    ]
