# Generated by Django 5.2.1 on 2025-06-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_utilisateur_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('fournisseur', 'Fournisseur'), ('distributeur', 'Distributeur'), ('gerant', 'Gerant_Pharmacie'), ('client', 'consomateur')], max_length=20),
        ),
    ]
